services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "xpack.security.enabled=true"
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/ || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD} "
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5601/ || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
  apm-server:
    container_name: elastic-apm
    image: docker.elastic.co/apm/apm-server:7.16.0
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    ports:
      - "8200:8200"
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      apm-server -e
         -E elastic.apm.secret.token=${APM_SECRET_TOKEN} 
         -E output.elasticsearch.enabled=true
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
         -E output.elasticsearch.protocol=http
         -E output.elasticsearch.username=elastic
         -E output.elasticsearch.password=${ELASTIC_PASSWORD} 
         -E output.elasticsearch.ssl.enabled=false
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8200/ || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  application:
    image: application
    ports:
      - "80:8080"
    build:
      context: .
      dockerfile: Api/Dockerfile